project_id = "mjylkefxurazemvbrhgj"

[functions.place-bid]
verify_jwt = true

[functions.accept-bid]
verify_jwt = true

[functions.admin-stats]
verify_jwt = true

[functions.create-paymob-payment]
verify_jwt = true

[functions.paymob-webhook]
verify_jwt = false

[functions.release-escrow-funds]
verify_jwt = true